import { ethers } from "ethers";

// ABIs - typically generated by TypeChain, simplified here for demo
const IDENTITY_REGISTRY_ABI = [
  "function register(bytes32 agentId, bytes32 profileHash) external",
  "function updateProfile(bytes32 agentId, bytes32 newProfileHash) external",
  "function profiles(bytes32) view returns (address owner, bytes32 profileHash, uint256 registeredAt, bool active)"
];

const REPUTATION_REGISTRY_ABI = [
  "function submitFeedback(bytes32 agentId, uint8 score, string calldata description) external",
  "function getFeedbackCount(bytes32 agentId) view returns (uint256)"
];

const VALIDATION_REGISTRY_ABI = [
  "function requestValidation(bytes32 agentId, address auditor) external returns (uint256)"
];

export class AgentRegistryClient {
  private identityContract: ethers.Contract;
  private reputationContract: ethers.Contract;
  private validationContract: ethers.Contract;

  constructor(
    identityAddress: string,
    reputationAddress: string,
    validationAddress: string,
    private signerOrProvider: ethers.Signer | ethers.Provider
  ) {
    this.identityContract = new ethers.Contract(identityAddress, IDENTITY_REGISTRY_ABI, signerOrProvider);
    this.reputationContract = new ethers.Contract(reputationAddress, REPUTATION_REGISTRY_ABI, signerOrProvider);
    this.validationContract = new ethers.Contract(validationAddress, VALIDATION_REGISTRY_ABI, signerOrProvider);
  }

  async registerAgent(agentId: string, profileHash: string) {
    const tx = await this.identityContract.register(agentId, profileHash);
    return tx.wait();
  }

  async getAgentProfile(agentId: string) {
    return this.identityContract.profiles(agentId);
  }

  async submitFeedback(agentId: string, score: number, description: string) {
    const tx = await this.reputationContract.submitFeedback(agentId, score, description);
    return tx.wait();
  }

  async requestValidation(agentId: string, auditorAddress: string) {
    const tx = await this.validationContract.requestValidation(agentId, auditorAddress);
    return tx.wait();
  }
}
